### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by yangroro** [luaneyed/angchelin#2]

**Comment by luaneyed** [comment]
Hi, yangroro! 👋

I was a little tight to keep this repository up to date in recent months 😅
But I am planning a major update! A bunch of fine restaurants will be added to angchelin soon.
Please look forward to new selections! 

I'm sorry for replying too late 😭

**Comment by yangroro** [comment]
👍 😄

**Comment by luaneyed** [comment]
@yangroro 약간의 밸런스 조절 및 장소 13군데 추가를 했습니다! 😋
