### ISSUE TITLE
add baekchae

### ISSUE THREAD

**Issue by 9oelM** [luaneyed/angchelin#3]
## Description of the problem
- Baekchae kimchi soup is my soul food

## Reason
- You also have tasted Baekchae multiple times with me
- And it was nice

## Conclusion
- You should put Baekchae kimchijjigae into the list

**Comment by luaneyed** [comment]
Thank you for reminding me of baekchae 👍

I'll consider your suggestion as soon as possible 🙂

**Comment by luaneyed** [comment]
4dd4dbd2451c0787530d4518ca02e5228f45e000
